<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>addEmployeeDetailsFromDataDriven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>668581f8-45a9-4b83-9b15-4e7556fd3a1b</testSuiteGuid>
   <testCaseLink>
      <guid>233fe51e-0c3b-4427-b7f8-438ce106f17a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/EmployeeDetails/addEmployeeDetailsFromDataDriven</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fc32c4a4-c1df-4e4a-b30a-816f0fc343d0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/EmployeeDetails/EmployeeDetails</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>fc32c4a4-c1df-4e4a-b30a-816f0fc343d0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FirstName</value>
         <variableId>c9386b68-e2c0-432f-b976-8c20551f13b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fc32c4a4-c1df-4e4a-b30a-816f0fc343d0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LastName</value>
         <variableId>7ff2cb0b-ed6e-4c93-ba19-c31209434d77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fc32c4a4-c1df-4e4a-b30a-816f0fc343d0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Age</value>
         <variableId>7755f78a-4e90-4354-af25-d54d04a9c56d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
